name: my first workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:   
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: welcome message 
          run: echo "This is what my first github actions first job testing"


        - name: List the files
          run: ls 
        - name: list all the hidden files to
          run: ls -a   

        - name: Display the stoage
          run: df -h