name: Workflow with sequence multiple jobs

on: push

jobs: 
    Build_job_1: 
        runs-on: ubuntu-latest
        steps:   
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: installing and testing cowsay program
          run: |
            sudo apt-get install cowsay -y
            cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR" >> dragon.txt
        - name: upload the artifact
          uses: actions/upload-artifact@v4
          with:
           name: dragon.file.txt
           path: dragon.txt


    test_job_2:
        needs: Build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: Download the artifact
          uses: actions/download-artifact@v4
          with:
            name: dragon.file.txt
    
    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
        - name: Download the artifact
          uses: actions/download-artifact@v4
          with:
            name: dragon.file.txt 
            
        - name: read the file
          run: |
           cat dragon.txt
           echo "deploying ........"