name: my Shell Script workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:   
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Executing the shell script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh